#docker-compose regular
seleniumhub:
  image: selenium/hub
  ports:
    - 4444:4444

chromenode:
  image: selenium/node-chrome
  environment:
    SCREEN_WIDTH: 1920
    SCREEN_HEIGHT: 1080
    NODE_MAX_INSTANCES: 2
    NODE_MAX_SESSION: 2
  ports:
    - 32770-32777:5900
  links:
    - seleniumhub:hub

# firefoxnode:
#   image: selenium/node-firefox-debug
#   environment:
#     SCREEN_WIDTH: 1920
#     SCREEN_HEIGHT: 1080
#     NODE_MAX_INSTANCES: 2
#     NODE_MAX_SESSION: 2
#   ports:
#     - 32770-32774:5900
#   links:
#     - seleniumhub:hub
